### ISSUE TITLE
Help Buttons on GUI filled

### ISSUE THREAD

**Issue by andrewsbryanc** [tbixler1/COSC-481W-Project-Scheduling-#17]
This issue will concern the output for the question mark help dialog box that will instruct the user what to do with the interface that they're currently looking at.  This issue corresponds only to the buttons being filled with the information, not the information itself.

**Comment by tgautz** [comment]
I'm confused...aren't the buttons already fully functional, except for needing the long string to place into the window?

**Comment by andrewsbryanc** [comment]
I added the ones we already have done so we can get a good feel of how far
we have gotten

**Comment by tgautz** [comment]
So.......we can close this issue....?

**Comment by andrewsbryanc** [comment]
Can do!
