### ISSUE TITLE
Read/Write to Database (Tutor List)

### ISSUE THREAD

**Issue by andrewsbryanc** [tbixler1/COSC-481W-Project-Scheduling-#19]
This issue will include the capabilities of reading and writing the tutor list to database.  If I'm under the right impression, the database will have the Tutor Lists and Unfinished Schedules in separate databases? Feel free to correct me on any of this.

**Comment by tgautz** [comment]
Only TutorInfo objects (tutors) I do believe.
See comment on issue #20 for further opinion/description.

**Comment by andrewsbryanc** [comment]
Sweet sounds good, let me know if we have the entire read write for the .tut files ready and I'll mark this closed.

**Comment by tgautz** [comment]
Tutor files are still in the works I do believe.  Keep issue open for now

**Comment by tbixler1** [comment]
Reading and writing are done. I'm going to close this issue. One thing to note is that the database file currently in master(the most recent version) has loops to read ints/bools however these loops are shorter than they should be they run for 5 iterations. Make sure you change or it will throw the whole thing off. I'll be opening a new issue to write update function.
