### ISSUE TITLE
Read/Write to Database (Unfinished Schedule)

### ISSUE THREAD

**Issue by andrewsbryanc** [tbixler1/COSC-481W-Project-Scheduling-#20]
This will include being able to read and write to the database that will have the unfinished schedules in it.

**Comment by tgautz** [comment]
I didn't think the database would be storing this information.  As it currently stands, I have the program creating .sch files, reading, and rewriting perfectly fine.
If there's no objection, I propose closing this issue.

**Comment by andrewsbryanc** [comment]
Sounds good, I'm creating these just so we can get a good track of what is and needs to be done.
