### ISSUE TITLE
Excel outputting from Java (creating the file)

### ISSUE THREAD

**Issue by andrewsbryanc** [tbixler1/COSC-481W-Project-Scheduling-#24]
This issue will involve getting Java to output to a Microsoft Excel WorkBook (the workbook is important!) We need to be able to create 3 Microsoft Excel WorkSheets, one for each of the outputs of our project.  This specific issue will show progress on the code actually creating the Excel file with 3 Worksheets, once the code outputs a workbook with 3 worksheets in it, this issue can be marked complete.

**Comment by tgautz** [comment]
```
    JFileChooser fc = new JFileChooser();
    int choice = fc.showOpenDialog(null);
    if(choice == JFileChooser.APPROVE_OPTION)
    {
        String path = fc.getSelectedFile().getAbsolutePath()+".xls";

        try {
            WritableWorkbook wBook = Workbook.createWorkbook(new File(path));
            WritableSheet sheet1 = wBook.createSheet("Sheet1",0);
            WritableSheet sheet2 = wBook.createSheet("sheet2",1);
            WritableSheet sheet3 = wBook.createSheet("sheeeeet3",2);
            wBook.write();
            wBook.close();



        } catch (Exception ex) {}
        try {
            Desktop.getDesktop().open(new File(path));
        } catch (IOException ex) {}
    }
```

**Comment by tgautz** [comment]
There you go, it asks which file to save to, names the sheets, and opens the excel file for viewing.
