### ISSUE TITLE
Excel outputting from Java (Formatting finished data)

### ISSUE THREAD

**Issue by andrewsbryanc** [tbixler1/COSC-481W-Project-Scheduling-#28]
This issue will involve properly formatting the finished excel sheet with the scheduled heuristic, as so it looks clean and legible.  Once we modify the code that outputs the finished heuristic to the excel file so that it has proper formatting and cell borders and such, we can mark this issue complete.

**Comment by Psybrnetk** [comment]
Run the latest ExcelOutput-12-6-15.java with a schedule and let me know if there are any problems. I haven't added in cell borders yet. Based on the resources I found online, the cells should autosize.
