### ISSUE TITLE
Excel outputting from Java (Reading the complete Schedule)

### ISSUE THREAD

**Issue by andrewsbryanc** [tbixler1/COSC-481W-Project-Scheduling-#29]
This issue will involve writing the code that can interpret our finished schedule for the data that we will need for each of the three Excel sheets.  The first sheet will need code that can read the finished schedule and figure out who works each hour and puts it to each time block on the Excel sheet (this should be the easiest), the second sheet will need code that can read the schedule for each tutor and gather all of the time blocks each tutor works so the sheet can show all of the hours each tutor works, and the third sheet will need code that can read the finished schedule for each subject and gather all of the time blocks each subject is offered so that the sheet can show all the hours each subject is offered.  This part may be the most difficult part of finishing the Excel output, but feel free to comment to me about it.

**Comment by Psybrnetk** [comment]
I think I have this finished but haven't tested it. See ExcelOutput-12-6-15.java. Each schedule should be created at the same time, on an individual sheet in the workbook.
