### ISSUE TITLE
Final GUI debugging

### ISSUE THREAD

**Issue by tgautz** [tbixler1/COSC-481W-Project-Scheduling-#31]
GUI needs a final debugging and cleaning once the database is finished and the rest of the GUI milestone is completed.

**Comment by andrewsbryanc** [comment]
This can be done, I think we should all try and "break" the GUI when we get the chance after we finish all other GUI related tasks.

**Comment by tgautz** [comment]
I agree.

**Comment by tgautz** [comment]
GUI is in the master branch.  If no issues/complaints arise by Saturday the 5th, then this will be closed.  You all have about a week to break the GUI.  Good luck.

**Comment by andrewsbryanc** [comment]
I wasn't able to break anything on it from my laptop, given the fact I was unable to see the full screen, but I'll test the last bit after work. On another note, I have my write up of the help menu dialogue boxes, do we have the other write up for comparison from the other guys?

**Comment by tgautz** [comment]
I haven't seen any writeups yet.  We can ask tomorrow in class to make sure.

**Comment by tgautz** [comment]
Not contested
